version: "3"
services:
  teamcity:
    image: jetbrains/teamcity-server
    volumes:
      - ./data/:/data/teamcity_server/datadir
      - ./logs/:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent 
    depends_on:
      - teamcity
    volumes:
      - ./agent/:/data/teamcity_agent/conf
    environment:
      SERVER_URL: "http://teamcity:8111"